[package]
name = "tokio_db_wrapper"
version = "0.1.0"
edition = "2021"

[profile.release]
panic = 'abort'

[dependencies]
futures = "0.3"
tokio = { version = "1.34.0", features = ["full"] }
tokio-postgres = "0.7.10"
once_cell = "1.3.1"
serde = "1.0"
serde_yaml = "0.9"
serde_derive = "1.0.193"